name: fetch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次（简化了cron表达式）

env:
  NODE_VERSION: 21.5.0

jobs:
  fetchurl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install

      - name: Run fetch script
        run: node fetchURLByAndroid720p.js  # 根据实际需要选择脚本

      - name: Commit changes
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update by GitHub Actions"

      - name Push changes
        uses ad-m/github-push-action@v0
        with:
          github_token ${{ secrets.GITHUB_TOKEN }}
          branch main
